name: happymusic
description: Music app made with â¤ in flutter at Karmaleen Technology

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  responsive_sizer: ^3.0.5+1 #Responsive Layout Helper
  persistent_bottom_nav_bar_v2: ^4.1.10 #Animated Bottom NavBar
  carousel_slider: ^4.1.1

  just_audio: ^0.9.21
  audio_session: ^0.1.5
  miniplayer: ^1.0.1
  flutter_riverpod: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"


flutter:

  uses-material-design: true

  assets:
    - assets/